### ISSUE TITLE
Fails on Ubuntu with Node 5.12.0

### ISSUE THREAD

**Issue by oniseijin** [mnichols/taped-electron#1]
Works on OS X just fine, but on Ubuntu 14 LTS
node v5.12.0 npm v3.8.6, &  v4.4.7 npm  v2.15.8: simply get an exit status of 1

running it as a script, not globally. 

Trace: 

<pre>                                                                                                                                                  1,1           All
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run-script', 'test' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle EDM@0.1.14~pretest: EDM@0.1.14
6 silly lifecycle EDM@0.1.14~pretest: no script for pretest, continuing
7 info lifecycle EDM@0.1.14~test: EDM@0.1.14
8 verbose lifecycle EDM@0.1.14~test: unsafe-perm in lifecycle true
9 verbose lifecycle EDM@0.1.14~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/lib/jenkins/jobs/EDM_electron/workspace/node_modules/.bin:/usr/bin:/var/lib/jenkins/share/java/BladeRunnerJS/sdk:./:/opt/flex/sdk3.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle EDM@0.1.14~test: CWD: /var/lib/jenkins/jobs/EDM_electron/workspace
11 silly lifecycle EDM@0.1.14~test: Args: [ '-c', 'taped-electron --main src/browser/main.js' ]
12 silly lifecycle EDM@0.1.14~test: Returned: code: 1  signal: null
13 info lifecycle EDM@0.1.14~test: Failed to exec test script
14 verbose stack Error: EDM@0.1.14 test: `taped-electron --main src/browser/main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid EDM@0.1.14
16 verbose cwd /var/lib/jenkins/jobs/EDM_electron/workspace
17 error Linux 3.13.0-24-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "test"
19 error node v5.12.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error EDM@0.1.14 test: `taped-electron --main src/browser/main.js`
22 error Exit status 1
23 error Failed at the EDM@0.1.14 test script 'taped-electron --main src/browser/main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the EDM package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     taped-electron --main src/browser/main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs EDM
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls EDM
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]</pre>

**Comment by mnichols** [comment]
Thanks @oniseijin . What version of electron are you using? Did you try with a more recent node?

**Comment by oniseijin** [comment]
Electron 1.2.7. Have not tried on 6 yet, but works fine with 5.0 on OSX 10.11

**Comment by mnichols** [comment]
ok. i'll fire up a linux vm and try to repro.  Basically I'll just run the repo tests via `npm test` on a linux environment. You should have two passing/two failing tests. Will report back!
